#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 CESNET.
#
# OARepo Micro API is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

set -e

ADMIN_PASSWORD=${OAREPO_ADMIN_PASSWORD:-OARepoAdm1n}

export FLASK_APP=video_repository_api/wsgi.py

oarepo setup "$ADMIN_PASSWORD" --drop-taxonomies --verbose
