#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 CESNET.
#
# OARepo Micro API is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.


export FLASK_DEBUG=true
export FLASK_ENV=deveopment
export SERVER_NAME=127.0.0.1:5000
#export FLASK_APP=video_repository_api.wsgi:application
export INVENIO_USER=$(id -u)

uwsgi --ini ./docker/uwsgi/uwsgi_http_custom.ini
